${template_header}
//
//  Publisher+Concurrency.swift
// 
//
//  Created by Sergej Jaskiewicz on 28.08.2021.
//

%{
instantiations = [('AsyncPublisher', False), ('AsyncThrowingPublisher', True)]
}%
% for instantiation, throwing in instantiations:
extension Publisher ${'' if throwing else 'where Failure == Never '}{

    /// The elements produced by the publisher, as ${'a throwing' if throwing else 'an'} asynchronous sequence.
    ///
    /// This property provides an `${instantiation}`, which allows you to use
    /// the Swift `async`-`await` syntax to receive the publisher's elements.
    /// Because `AsyncPublisher` conforms to `AsyncSequence`, you iterate over its
    /// elements with a `for`-`await`-`in` loop, rather than attaching a subscriber.
% if throwing:
    /// If the publisher terminates with an error, the awaiting caller receives the error
    /// as a `throw`.
% end
    @available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public var values: ${instantiation}<Self> {
        return .init(self)
    }
}

/// A publisher that exposes its elements as ${'a throwing' if throwing else 'an'} asynchronous sequence.
///
/// `${instantiation}` conforms to `AsyncSequence`, which allows callers to receive
/// values with the `for`-`await`-`in` syntax, rather than attaching a `Subscriber`.
% if throwing:
/// If the upstream publisher terminates with an error, `${instantiation}` throws
/// the error to the awaiting caller.
% end
///
/// Use the `values` property of the `Publisher` protocol to wrap an existing publisher
/// with an instance of this type.
@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
public struct ${instantiation}<Upstream: Publisher>: AsyncSequence
%   if not throwing:
    where Upstream.Failure == Never
%   end
{

    public typealias Element = Upstream.Output

    /// The iterator that produces elements of the asynchronous publisher sequence.
    public struct Iterator: AsyncIteratorProtocol {

        public typealias Element = Upstream.Output

        fileprivate let inner: Inner

        /// Produces the next element in the prefix sequence.
        ///
        /// - Returns: The next published element, or `nil` if the publisher finishes
        ///   normally.
% if throwing:
        ///   If the publisher terminates with an error, the call point receives
        ///   the error as a `throw`.
% end
        public mutating func next() async ${'throws ' if throwing else ''}-> Element? {
            return ${'try ' if throwing else ''}await withTaskCancellationHandler(
                operation: { [inner] in ${'try ' if throwing else ''}await inner.next() },
                onCancel: { [inner] in inner.cancel() }
            )
        }
    }

    /// The type of asynchronous iterator that produces elements of this
    /// asynchronous sequence.
    public typealias AsyncIterator = Iterator

    private let publisher: Upstream

    /// Creates a publisher that exposes elements received from an upstream publisher as
% if throwing:
    /// an asynchronous sequence.
% else:
    /// a throwing asynchronous sequence.
% end
    ///
    /// - Parameter publisher: An upstream publisher. The asynchronous publisher converts
    ///   elements received from this publisher into an asynchronous sequence.
    public init(_ publisher: Upstream) {
        self.publisher = publisher
    }

    /// Creates the asynchronous iterator that produces elements of this asynchronous
    /// sequence.
    ///
    /// - Returns: An instance of the `AsyncIterator` type used to produce elements of
    ///   the asynchronous sequence.
    public func makeAsyncIterator() -> Iterator {
        let inner = Iterator.Inner()
        publisher.subscribe(inner)
        return Iterator(inner: inner)
    }
}

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
extension ${instantiation}.Iterator {

    fileprivate final class Inner: Subscriber, Cancellable {
        typealias Input = Upstream.Output
        typealias Failure = Upstream.Failure

        private enum State {
            case awaitingSubscription
            case subscribed(Subscription)
            case terminal${'(Error?)' if throwing else ''}
        }

        private let lock = UnfairLock.allocate()
        private var pending: [UnsafeContinuation<Input?, ${'Error' if throwing else 'Never'}>] = []
        private var state = State.awaitingSubscription
        private var pendingDemand = Subscribers.Demand.none

        deinit {
            lock.deallocate()
        }

        func receive(subscription: Subscription) {
            lock.lock()
            guard case .awaitingSubscription = state else {
                lock.unlock()
                subscription.cancel()
                return
            }
            state = .subscribed(subscription)
            let pendingDemand = self.pendingDemand
            self.pendingDemand = .none
            lock.unlock()
            if pendingDemand != .none {
                subscription.request(pendingDemand)
            }
        }

        func receive(_ input: Input) -> Subscribers.Demand {
            lock.lock()
            guard case .subscribed = state else {
                let pending = self.pending.take()
                lock.unlock()
                pending.resumeAllWithNil()
                return .none
            }
            precondition(!pending.isEmpty, "Received an output without requesting demand")
            let continuation = pending.removeFirst()
            lock.unlock()
            continuation.resume(returning: input)
            return .none
        }

        func receive(completion: Subscribers.Completion<Failure>) {
            lock.lock()
%   if throwing:
            switch state {
            case .awaitingSubscription, .subscribed:
                if let continuation = pending.first {
                    state = .terminal(nil)
                    let remaining = pending.take().dropFirst()
                    lock.unlock()
                    switch completion {
                    case .finished:
                        continuation.resume(returning: nil)
                    case .failure(let error):
                        continuation.resume(throwing: error)
                    }
                    remaining.resumeAllWithNil()
                } else {
                    state = .terminal(completion.failure)
                    lock.unlock()
                }
            case .terminal:
                let pending = self.pending.take()
                lock.unlock()
                pending.resumeAllWithNil()
            }
%   else:
            state = .terminal
            let pending = self.pending.take()
            lock.unlock()
            pending.resumeAllWithNil()
%   end
        }

        func cancel() {
            lock.lock()
            let pending = self.pending.take()
            guard case .subscribed(let subscription) = state else {
                state = .terminal${'(nil)' if throwing else ''}
                lock.unlock()
                pending.resumeAllWithNil()
                return
            }
            state = .terminal${'(nil)' if throwing else ''}
            lock.unlock()
            subscription.cancel()
            pending.resumeAllWithNil()
        }

        fileprivate func next() async ${'throws ' if throwing else ''}-> Input? {
            return ${'try ' if throwing else ''}await withUnsafe${'Throwing' if throwing else ''}Continuation { continuation in
                lock.lock()
                switch state {
                case .awaitingSubscription:
                    pending.append(continuation)
                    pendingDemand += 1
                    lock.unlock()
                case .subscribed(let subscription):
                    pending.append(continuation)
                    lock.unlock()
                    subscription.request(.max(1))
                case .terminal${'(nil)' if throwing else ''}:
                    lock.unlock()
                    continuation.resume(returning: nil)
%   if throwing:
                case .terminal(let error?):
                    state = .terminal(nil)
                    lock.unlock()
                    continuation.resume(throwing: error)
%   end
                }
            }
        }
    }
}
% end

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
extension Sequence {
    fileprivate func resumeAllWithNil<Output, Failure: Error>()
        where Element == UnsafeContinuation<Output?, Failure>
    {
        for continuation in self {
            continuation.resume(returning: nil)
        }
    }
}
